project:
  crs: "EPSG:4326"
  layers: 
  - csvPath: "/home/kevin/proj/MapMyCsv/sample.csv"
    crs:     "EPSG:4326"
    color:   "red"
  - csvPath: "/home/kevin/proj/MapMyCsv/sample2.csv"
    color: "blue"
